//
//  CleanupPlan.swift
//  PulseCore
//
//  Pure data types for cleanup planning and results.
//  No AppKit, SwiftUI, ObservableObject, or @Published.
//

import Foundation

// MARK: - Cleanup Profile

/// Profiles available for cleanup. v0.1 only supports Xcode.
public enum CleanupProfile: String, CaseIterable {
    case xcode
    // v0.2: case homebrew, case node, case docker, case browser, case system
}

// MARK: - Cleanup Config

/// Configuration for a cleanup scan/apply operation.
/// This is the ONLY interface between PulseApp and PulseCore.
/// No ObservableObject, no @Published, no singleton, no UserDefaults.
public struct CleanupConfig {
    /// Which profiles to include in the scan.
    public var profiles: Set<CleanupProfile>

    /// User-defined paths to always skip during cleanup.
    public var excludedPaths: [String]

    public init(
        profiles: Set<CleanupProfile> = [.xcode],
        excludedPaths: [String] = []
    ) {
        self.profiles = profiles
        self.excludedPaths = excludedPaths
    }
}

// MARK: - Cleanup Priority

/// Priority levels for cleanup items.
/// Higher priority = safer to delete, more recommended.
public enum CleanupPriority: String, CaseIterable, Codable, Comparable {
    case high = "High"
    case medium = "Medium"
    case low = "Low"
    case optional = "Optional"

    /// Comparable: high > medium > low > optional
    public static func < (lhs: CleanupPriority, rhs: CleanupPriority) -> Bool {
        lhs.sortOrder > rhs.sortOrder
    }

    private var sortOrder: Int {
        switch self {
        case .high: return 0
        case .medium: return 1
        case .low: return 2
        case .optional: return 3
        }
    }
}

// MARK: - Cleanup Category

/// Categories for cleanup items.
public enum CleanupCategory: String, CaseIterable {
    case developer = "Developer"
    case browser = "Browser"
    case application = "Applications"
    case system = "System"
    case logs = "Logs"
}

// MARK: - Cleanup Plan

/// A plan of what can be cleaned, generated by a dry-run scan.
public struct CleanupPlan {
    public let items: [CleanupItem]
    public let warnings: [CleanupWarning]
    public let totalSizeMB: Double
    public let timestamp: Date

    public init(items: [CleanupItem], warnings: [CleanupWarning] = [], totalSizeMB: Double, timestamp: Date = Date()) {
        self.items = items
        self.warnings = warnings
        self.totalSizeMB = totalSizeMB
        self.timestamp = timestamp
    }

    public var totalSizeText: String {
        if totalSizeMB > 1024 {
            return String(format: "%.1f GB", totalSizeMB / 1024)
        }
        return String(format: "%.0f MB", totalSizeMB)
    }

    public var itemCount: Int { items.count }
    public var warningCount: Int { warnings.count }
    public var isSignificant: Bool { totalSizeMB > 50 }

    public struct CleanupItem {
        public let name: String
        public let sizeMB: Double
        public let category: CleanupCategory
        public let path: String
        public let isDestructive: Bool
        public let requiresAppClosed: Bool
        public let appName: String?
        public let warningMessage: String?
        public let priority: CleanupPriority
        public var skipReason: String?

        public init(
            name: String,
            sizeMB: Double,
            category: CleanupCategory,
            path: String,
            isDestructive: Bool,
            requiresAppClosed: Bool,
            appName: String?,
            warningMessage: String?,
            skipReason: String? = nil,
            priority: CleanupPriority = .medium
        ) {
            self.name = name
            self.sizeMB = sizeMB
            self.category = category
            self.path = path
            self.isDestructive = isDestructive
            self.requiresAppClosed = requiresAppClosed
            self.appName = appName
            self.warningMessage = warningMessage
            self.skipReason = skipReason
            self.priority = priority
        }

        public var sizeText: String {
            if sizeMB > 1024 {
                return String(format: "%.1f GB", sizeMB / 1024)
            }
            return String(format: "%.0f MB", sizeMB)
        }
    }

    public struct CleanupWarning {
        public let message: String
        public let appName: String
        public let itemsAffected: Int

        public init(message: String, appName: String, itemsAffected: Int) {
            self.message = message
            self.appName = appName
            self.itemsAffected = itemsAffected
        }
    }
}

// MARK: - Cleanup Result

/// Result of an actual cleanup operation.
public struct CleanupResult {
    public let steps: [Step]
    public let skipped: [SkippedItem]
    public let totalFreedMB: Double
    public let timestamp: Date

    public init(steps: [Step], skipped: [SkippedItem] = [], totalFreedMB: Double, timestamp: Date = Date()) {
        self.steps = steps
        self.skipped = skipped
        self.totalFreedMB = totalFreedMB
        self.timestamp = timestamp
    }

    public var summary: String {
        let successCount = steps.filter(\.success).count
        if totalFreedMB > 1024 {
            return "\(successCount) actions · \(String(format: "%.1f GB", totalFreedMB / 1024)) freed"
        }
        return "\(successCount) actions · \(String(format: "%.0f MB", totalFreedMB)) freed"
    }

    public var successCount: Int { steps.filter(\.success).count }
    public var failureCount: Int { steps.filter { !$0.success }.count }

    public struct Step {
        public let name: String
        public let freedMB: Double
        public let success: Bool
        public let category: CleanupCategory?

        public init(name: String, freedMB: Double, success: Bool, category: CleanupCategory? = nil) {
            self.name = name
            self.freedMB = freedMB
            self.success = success
            self.category = category
        }
    }

    public struct SkippedItem {
        public let name: String
        public let reason: String
        public let sizeMB: Double

        public init(name: String, reason: String, sizeMB: Double) {
            self.name = name
            self.reason = reason
            self.sizeMB = sizeMB
        }
    }
}
